
[functions.send_contact_email]
enabled = true
verify_jwt = true
import_map = "./functions/send_contact_email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send_contact_email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send_contact_email/*.html" ]

[functions.delete_account]
enabled = true
verify_jwt = true
import_map = "./functions/delete_account/deno.json"
entrypoint = "./functions/delete_account/index.ts"
