name: ridewealth_assistant
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2 
  fluttertoast: ^8.2.4
  cloud_firestore: ^4.15.9
  shared_preferences: ^2.2.2
  csv: ^5.1.1
  http: ^1.1.2
  intl: ^0.19.0
  universal_html: ^2.2.4
  path_provider: ^2.1.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/