name: ridewealth_assistant
description: A financial assistant for rideshare and gig drivers.

publish_to: "none"

version: 1.0.23+24

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.1"

dependencies:
  flutter:
    sdk: flutter
  english_words:
  provider:
  shared_preferences: ^2.3.3
  csv: ^5.1.1
  http: ^1.1.2
  intl: ^0.19.0
  universal_html: ^2.2.4
  path_provider: ^2.1.2
  collection: ^1.18.0
  fluttertoast: ^8.2.8
  url_launcher: ^6.3.1
  in_app_purchase: ^3.1.13
  in_app_purchase_android: ^0.3.6+7
  share_plus: ^11.0.0
  permission_handler: ^11.3.1
  in_app_purchase_storekit: ^0.3.0
  supabase_flutter:
  connectivity_plus: ^5.0.2
  dynamic_color: ^1.6.8
  purchases_flutter: ^8.10.5
  flutter_plugin_android_lifecycle: ^2.0.15
  flutter_svg: ^2.0.9
  sentry_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/googlelogo.svg
    - assets/applelogo.svg
    - RWAlogo.png
    - rwacar.png
    - dollarsign.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "RWAlogo.png"
  web:
    generate: true
    image_path: "RWAlogo.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"
# St. Carlo, pray for us
# St. Joseph, pray for us
# St. Michael, the Archangel, pray for us
# St. Matthew, pray for us
