name: ridewealth_assistant
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  cloud_firestore: ^4.17.5
  shared_preferences: ^2.2.2
  csv: ^5.1.1
  http: ^1.1.2
  intl: ^0.19.0
  universal_html: ^2.2.4
  path_provider: ^2.1.2
  collection: ^1.18.0
  firebase_crashlytics: ^3.5.7
  logging: ^1.2.0
  crypto: ^3.0.3
  fluttertoast: ^8.2.8
  url_launcher: ^6.3.1
  in_app_purchase: ^3.1.5
  file_picker: ^6.2.1
  share_plus: ^10.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
