name: ridewealth_assistant
description: A financial assistant for rideshare and gig drivers.

publish_to: "none"

version: 1.0.17+17

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.1"

dependencies:
  flutter:
    sdk: flutter
  english_words:
  provider:
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  shared_preferences: ^2.3.4
  csv: ^5.1.1
  http: ^1.1.2
  intl: ^0.19.0
  universal_html: ^2.2.4
  path_provider: ^2.1.2
  collection: ^1.18.0
  fluttertoast: ^8.2.8
  url_launcher: ^6.3.1
  in_app_purchase: ^3.2.3
  share_plus: ^11.0.0
  permission_handler: ^12.0.1
  in_app_purchase_android: ^0.4.0+2
  in_app_purchase_storekit: ^0.4.3
  supabase_flutter:
  flutter_dotenv:
  connectivity_plus: ^5.0.2
  dynamic_color: ^1.6.8
  purchases_flutter: ^8.10.5
  flutter_plugin_android_lifecycle: ^2.0.15
  google_sign_in_android: ^6.1.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env

# St. Carlo, pray for us
# St. Joseph, pray for us
# St. Michael, the Archangel, pray for us
# St. Matthew, pray for us